pool:
  name: 'Default'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  BUILD_BUILDNUMBER: $(Build.BuildNumber)

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  displayName: 'Restore Nuget Packages'
  inputs:
    restoreSolution: '$(solution)'

- task: DotNetCoreCLI@2
  displayName: 'Build Projects'
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '-c Release --no-restore'

- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: 'Chadwick.Database/Chadwick.Database.csproj'
    nobuild: true
    includesymbols: true
    includesource: true
    versioningScheme: 'byBuildNumber'
- task: NuGetCommand@2
  displayName: 'Push'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '2d954ad5-bc4f-4b9c-b431-f866236fe7ff'
    allowPackageConflicts: true
